defaults:
  - agent: ContinuousAgent
  - mcts: MCTSContinuous
  - optimizer: RMSProp
  - policy: ContinuousPolicy
  - loss: A0CLossTuned
    

game: MCPMod-v0
seed: 34
num_train_episodes: 45
max_episode_length: 200
num_train_epochs: 1
device: cpu

buffer:
  _target_: alphazero.agent.buffers.ReplayBuffer
  max_size: 3000
  batch_size: 32
