defaults:
  - agent: ContinuousAgent
  - loss: A0CLoss
  - hydra/sweeper: ax
    

game: Pendulum-v0
seed: 34
num_train_episodes: 100
max_episode_length: 200
num_train_epochs: 1
device: cpu

buffer:
  _target_: alphazero.buffers.ReplayBuffer
  max_size: 3000
  batch_size: 32
