defaults:
    - agent: DiscreteAgent
    - loss: AlphaZeroLoss

game: CartPole-v0
seed: 34
num_train_episodes: 200
max_episode_length: 200
device: cpu

buffer:
    _target_: alphazero.buffers.ReplayBuffer
    max_size: 1000
    batch_size: 32
