# @package _global_
agent:
    _target_: alphazero.agents.ContinuousAgent
    network_cfg: ${network}
    loss_cfg: ${loss}
    optimizer_cfg: ${network_optimizer}
    

network:
    _target_: alphazero.networks.NetworkContinuous
    state_dim: ??? # set later
    action_dim: ??? # set later
    act_limit: ??? # set later
    n_hidden_layers: 1
    n_hidden_units: 128

network_optimizer:
    _target_: torch.optim.RMSprop
    lr: 0.001
    alpha: 0.9
    eps: 1e-07

mcts:
    _target_: alphazero.mcts.MCTSContinuous
    n_rollouts: 25
    c_pw: 1
    kappa: 0.5
    gamma: 1
    c_uct: 0.05