# @package _global_
agent:
  _target_: alphazero.agents.ContinuousAgent
  network_cfg: ${network}
  mcts_cfg: ${mcts}
  loss_cfg: ${loss}
  optimizer_cfg: ${optimizer}
  train_epochs: ${num_train_epochs}
  final_selection: max_visit # can be max_visit or max_value
  grad_clip: 0
  device: ${device}
