# @package _global_
agent:
  _target_: alphazero.agents.DiscreteAgent
  is_atari: ??? # set later
  network_cfg: ${network}
  mcts_cfg: ${mcts}
  loss_cfg: ${loss}
  optimizer_cfg: ${optimizer}
  train_epochs: ${num_train_epochs}
  final_selection: max_visits # can be max_visits or max_counts
  grad_clip: 0
  temperature: 1.0
  device: ${device}
